# Generated by Django 2.2.5 on 2019-09-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prerequis', models.TextField(default='opérateurs numériques, opérateurs logiques, boucles')),
                ('introduction', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texte', models.TextField()),
                ('reponse', models.IntegerField()),
                ('points', models.IntegerField()),
                ('cout', models.IntegerField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portail.Chapitre')),
            ],
            options={
                'verbose_name': 'enigme',
                'ordering': ['numero'],
            },
        ),
    ]
