# Generated by Django 2.2.5 on 2019-09-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0002_auto_20190916_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': (['score'], ['date_lastscore']), 'verbose_name': 'Pseudo'},
        ),
    ]
