# Generated by Django 2.2.5 on 2019-09-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portail', '0003_auto_20190916_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ['-score', 'date_lastscore'], 'verbose_name': 'Pseudo'},
        ),
        migrations.CreateModel(
            name='EnigmeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.IntegerField(default=3)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portail.Chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
