# Generated by Django 2.2.5 on 2019-09-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0004_auto_20190919_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enigme',
            options={'ordering': ['chapitre'], 'verbose_name': 'enigme'},
        ),
        migrations.AlterModelOptions(
            name='enigmestatus',
            options={'ordering': ['chapitre']},
        ),
        migrations.RemoveField(
            model_name='enigme',
            name='cout',
        ),
        migrations.AddField(
            model_name='joueur',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='first',
            field=models.BooleanField(default=True),
        ),
    ]
