# Generated by Django 2.2.5 on 2019-09-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0005_auto_20190919_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='code',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
