# Generated by Django 2.2.5 on 2019-10-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0007_auto_20191003_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='couleurfond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portail.Couleur'),
        ),
    ]
