# Generated by Django 2.2.5 on 2019-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0008_auto_20191005_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='illustration',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
