# Generated by Django 2.2.5 on 2019-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0009_chapitre_illustration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='illustration',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image 500x500 px',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
