# Generated by Django 2.2.5 on 2019-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0012_auto_20191006_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='nb_bonnes_reponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='nb_reponses_donnees',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
