# Generated by Django 2.2.5 on 2019-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0013_auto_20191014_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='nb_reponses_donnees',
            field=models.IntegerField(default=0),
        ),
    ]
