# Generated by Django 2.2.5 on 2019-10-16 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0014_auto_20191014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='date_lastscore',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
