# Generated by Django 2.2.5 on 2019-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0015_auto_20191016_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joueur',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
    ]
