# Generated by Django 2.2.5 on 2019-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0016_auto_20191110_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='invite',
            field=models.BooleanField(default=False),
        ),
    ]
