# Generated by Django 2.2.5 on 2019-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0018_auto_20191114_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['index'], 'verbose_name': 'nom'},
        ),
        migrations.AddField(
            model_name='chapitre',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
